#!/usr/bin/env python

import roslib; roslib.load_manifest('memory')
import sys
import thread
import rospy

from memory.lib import *

if __name__ == "__main__":
    rospy.init_node('memory_read')
    c = MemoryClient('cmdline', ns=rospy.get_param('~memory_namespace', '/memory'))
    argv = rospy.myargv()
    term_id = argv[1]
    meta = c.read(term_id)
    print meta
