#!/usr/bin/env python

import roslib; roslib.load_manifest('memory')
from memory.msg import *
from memory.lib import *

if len(sys.argv) == 1:
    print('usage: term_parser <tok_1> <tok_2> ... <tok_n>')
else:
    toklist = list(str2token(s) for s in sys.argv[1:])
    print('token list: %s' % tokenlist2str(toklist))
    print('term: %s' % term2str(Term(tokens=toklist)))

    
