#!/usr/bin/env python

import roslib; roslib.load_manifest('memory')
import sys
import thread
import rospy

from memory.lib import *

if __name__ == "__main__":
    rospy.init_node('memory_write')
    c = MemoryClient('cmdline', ns=rospy.get_param('~memory_namespace', '/memory'))
    argv = rospy.myargv()
    term_id = argv[1]
    term = term_parse(argv[2:])
    c.write(term_id, term)
